# MySQL master address, user and password
# user must have replication privilege in MySQL.
my_addr = "192.168.0.170:3306"
my_user = "root"
my_pass = "123456"
my_charset = "utf8"

# Set true when elasticsearch use https
#es_https = false
# Elasticsearch address
#es_addr = "172.16.0.27:9288"
# Elasticsearch user and password, maybe set by shield, nginx, or x-pack
#es_user = ""
#es_pass = ""
# MySQL slave address, user and password
myto_addr = "192.168.0.204:3306"
myto_user = "root"
myto_pass = "yearning"
myto_charset = "utf8"
myto_maxcon=300
# Path to store data, like master.info, if not set or empty,
# we must use this to support breakpoint resume syncing. 
# TODO: support other storage, like etcd. 
data_dir = "./"

# Inner Http status address
stat_addr = "127.0.0.1:8989"

# pseudo server id like a slave 
server_id = 1987

# mysql or mariadb
flavor = "mysql"

# mysqldump execution path
# if not set or empty, ignore mysqldump.
mysqldump = ""

# if we have no privilege to use mysqldump with --master-data,
# we must skip it.
#skip_master_data = false

# minimal items to be inserted in one bulk
bulk_size = 128

# force flush the pending requests if we don't have enough items >= bulk_size
flush_bulk_time = "1ms"

# Ignore table without primary key
skip_no_pk_table = false

# MySQL data source
[[source]]
schema = "mytest"

# first table
[[rule]]
schema = "mytest"
table = "testtab"
index = "testtab"
type = "testtab"

#  sercond table
#
#
[[rule]]
schema = "mytest"
table = "test"
index = "test"
type = "test"
